config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_dunst:
    dst: ~/.config/dunst
    src: config/dunst
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  d_polybar:
    dst: ~/.config/polybar
    src: config/polybar
  d_rofi:
    dst: ~/.config/rofi
    src: config/rofi
  f_compton.conf:
    dst: ~/.config/compton.conf
    src: config/compton.conf
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  xps:
    dotfiles:
    - f_zshrc
    - d_i3
    - d_polybar
    - d_dunst
    - d_rofi
    - f_compton.conf
